# Generated by Django 5.1.3 on 2024-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Укажите локацию, в которой необходимо выполнять привычку', max_length=255, verbose_name='Локация')),
                ('time', models.TimeField(help_text='Установите время, когда необходимо выполнять привычку', verbose_name='Время выполнения привычки')),
                ('action', models.CharField(help_text='Укажите действие, которое нужно совершить', max_length=100, verbose_name='Активность')),
                ('estimated_time', models.IntegerField(verbose_name='Время потраченное на выполнение (в секундах)')),
                ('periodicity', models.IntegerField(default=1, help_text='Укажите периодичность выполнения привычки в днях (по умолчанию ежедневная)', verbose_name='Периодичность в днях')),
                ('nice_habit', models.BooleanField(blank=True, default=True, null=True, verbose_name='Приятная привычка')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликована')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-id'],
            },
        ),
    ]
