# Generated by Django 5.1.3 on 2024-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='Активность')),
                ('estimated_time', models.IntegerField(verbose_name='Время потраченное на выполнение (в секундах)')),
                ('periodicity', models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=False, verbose_name='Периодичность')),
                ('nice_habit', models.BooleanField(default=True, verbose_name='Приятная привычка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-id'],
            },
        ),
    ]
